# Generated by Django 3.2.11 on 2022-01-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of task')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('label', models.ManyToManyField(blank=True, to='labels.Label', verbose_name='Label')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statuses.status', verbose_name='Status')),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker', to=settings.AUTH_USER_MODEL, verbose_name='Worker')),
            ],
            options={
                'verbose_name_plural': 'Task',
            },
        ),
    ]
